@startuml

title shogi_ES2015

class Piece {
  id : 駒の種類
  name : 駒の名前
  order : 先手 or 後手
  move()
  movablePosition()
}

class Cell {
  +piece
}

class Table {
  +cell
}

class Panel {

}

class Shogi {
  +panel
  +table
}

Cell "1..*" o-- "1" Table
Table <-- Panel
Shogi --> Panel
Shogi --> Table

@enduml
